#!/bin/sh

# positional parameters:
# 1. path to code root (ie parent of TOCB and BA_SNAPSHOTS directories)

TOCB_REGEX="$1/TOCB-mainline/\d\d\d\d/"
BA_REGEX="$1/BA_SNAPSHOTS/\d\d\d\d/"

DATA_DIR=../../output_datasets/02_dependency_output/cpp_java

python3 dedup.py --output $DATA_DIR/final/TOCB_BA_2000_2013_CPP_JAVA.tsv \
        --input $DATA_DIR/csvs/tocb_C++_2000.csv                         \
        --repo tocb                                                      \
        --year 2000                                                      \
        --language C++                                                   \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_C++_2001.csv                         \
        --repo tocb                                                      \
        --year 2001                                                      \
        --language C++                                                   \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_C++_2002.csv                         \
        --repo tocb                                                      \
        --year 2002                                                      \
        --language C++                                                   \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_C++_2003.csv                         \
        --repo tocb                                                      \
        --year 2003                                                      \
        --language C++                                                   \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_C++_2004.csv                         \
        --repo tocb                                                      \
        --year 2004                                                      \
        --language C++                                                   \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_C++_2005.csv                         \
        --repo tocb                                                      \
        --year 2005                                                      \
        --language C++                                                   \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_C++_2006.csv                         \
        --repo tocb                                                      \
        --year 2006                                                      \
        --language C++                                                   \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_C++_2007.csv                         \
        --repo tocb                                                      \
        --year 2007                                                      \
        --language C++                                                   \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_Java_2000.csv                        \
        --repo tocb                                                      \
        --year 2000                                                      \
        --language Java                                                  \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_Java_2001.csv                        \
        --repo tocb                                                      \
        --year 2001                                                      \
        --language Java                                                  \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_Java_2002.csv                        \
        --repo tocb                                                      \
        --year 2002                                                      \
        --language Java                                                  \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_Java_2003.csv                        \
        --repo tocb                                                      \
        --year 2003                                                      \
        --language Java                                                  \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_Java_2004.csv                        \
        --repo tocb                                                      \
        --year 2004                                                      \
        --language Java                                                  \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_Java_2005.csv                        \
        --repo tocb                                                      \
        --year 2005                                                      \
        --language Java                                                  \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_Java_2006.csv                        \
        --repo tocb                                                      \
        --year 2006                                                      \
        --language Java                                                  \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/tocb_Java_2007.csv                        \
        --repo tocb                                                      \
        --year 2007                                                      \
        --language Java                                                  \
        --pathstem $TOCB_REGEX                                           \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2005.csv                           \
        --repo ba                                                        \
        --year 2005                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2006.csv                           \
        --repo ba                                                        \
        --year 2006                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2007.csv                           \
        --repo ba                                                        \
        --year 2007                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2008.csv                           \
        --repo ba                                                        \
        --year 2008                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2009.csv                           \
        --repo ba                                                        \
        --year 2009                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2010.csv                           \
        --repo ba                                                        \
        --year 2010                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2011.csv                           \
        --repo ba                                                        \
        --year 2011                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2012.csv                           \
        --repo ba                                                        \
        --year 2012                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_C++_2013.csv                           \
        --repo ba                                                        \
        --year 2013                                                      \
        --language C++                                                   \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2005.csv                          \
        --repo ba                                                        \
        --year 2005                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2006.csv                          \
        --repo ba                                                        \
        --year 2006                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2007.csv                          \
        --repo ba                                                        \
        --year 2007                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2008.csv                          \
        --repo ba                                                        \
        --year 2008                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2009.csv                          \
        --repo ba                                                        \
        --year 2009                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2010.csv                          \
        --repo ba                                                        \
        --year 2010                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2011.csv                          \
        --repo ba                                                        \
        --year 2011                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2012.csv                          \
        --repo ba                                                        \
        --year 2012                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \
                                                                         \
        --input $DATA_DIR/csvs/ba_Java_2013.csv                          \
        --repo ba                                                        \
        --year 2013                                                      \
        --language Java                                                  \
        --pathstem $BA_REGEX                                             \

