# -*- encoding: utf-8 -*-
#===================================================================================================
# Uses udbtools to operate upon an existing udb generated by Understand
# ontains functions to extract Dependencies and Entities
#===================================================================================================
#genJavaDep.py
#Created mshakir@keystonestrategy.com
#Modified ssia@keystonestrategy.com
#Last Modified 08/16/2016

import depScripts.udbtools
import depScripts.UdbSchemaJava
import sys

# This parameter controls the types of dependencies that we count.
# It is a list of lists of length 3.
# An internal list [ ent_type_1, dep_type, ent_type_2 ] means to count
# when an `ent_type_1` depends on an `ent_type_2` via a `dep_type`.
# Valid entity and dependency types are found in UdbSchemaJava.py.
DepRules = [
  ["File", "Import", "Type"],
  ["Method", "Call", "Method"],
  ["Type", "Couple", "Type"],
  ["Type", "Cast", "Type"],
]

# Entity types that do not have associated definition files.
# (Usually these are the entities that represent files themselves.)
NoFileEnts = { "File" }

# DepRules is turned into something like this:
"""
DepRules = {
  "Function": {
    "Call": [ Function ]
  },
  "Type": {
    "Base": [ "Type" ]
  }
}
"""

def genJavaDep(udbpath,csvpath):
  udb = depScripts.udbtools.UDB(udbpath)
  udb.setSpecs(depScripts.UdbSchemaJava.Language, depScripts.UdbSchemaJava.TypeMap, depScripts.UdbSchemaJava.RefMap, DepRules, NoFileEnts)
  udb.dumpDeps(csvpath)

def genJavaEnt(udbpath,csvpath):
  udb = depScripts.udbtools.UDB(udbpath)
  udb.setSpecs(depScripts.UdbSchemaJava.Language, depScripts.UdbSchemaJava.TypeMap, depScripts.UdbSchemaJava.RefMap, DepRules, NoFileEnts)
  udb.dumpEnts(csvpath)

if __name__ == "__main__":
  if len(sys.argv) < 3:
    print("Requires 2 arguments:")
    print("1. udb path (input)")
    print("2. csv path for deps (output)")
    print("3. csv path for ents (output)")

  udbpath = sys.argv[1]
  depcsvpath = sys.argv[2]
  entcsvpath = sys.argv[3]

  genJavaDep(udbpath,depcsvpath)
  genJavaEnt(udbpath,entcsvpath)

