import understand
import csv
import sys

Language = "C"

TypeMap = {
  "Asm": set([
    "C Asm File",
    "C Asm Function Global",
    "C Asm Function Local",
    "C Asm Header File",
    "C Asm Label Global",
    "C Asm Label Local",
    "C Asm Macro",
    "C Asm Macro Functional",
    "C Asm Parameter",
    "C Asm Section",
    "C Asm Symbol Global",
    "C Asm Symbol Local",
    "C Asm Unknown",
    "C Asm Unresolved Function",
    "C Asm Unresolved Header File",
    "C Asm Unresolved Macro",
  ]),
  "Enumerator": set([
    "C Enumerator",
    "C Private Member Enumerator",
    "C Protected Member Enumerator",
    "C Public Member Enumerator",
    "C Unresolved Enumerator",
    "C Unresolved Private Member Enumerator",
    "C Unresolved Protected Member Enumerator",
    "C Unresolved Public Member Enumerator",
  ]),
  "File": set([
    "C Code File",
    "C Header File",
    "C Unknown Header File",
    "C Unresolved Header File",
    "C Asm File",
    "C Asm Header File",
    "C Asm Unresolved Header File",
  ]),
  "Function": set([
    "C Function",
    "C Function Template",
    "C Function Interrupt",
    "C Function Interrupt Template",
    "C Function Interrupt Static",
    "C Function Interrupt Static Template",
    "C Function Static",
    "C Function Static Template",
    "C Private Member Const Function",
    "C Private Member Const Function Template",
    "C Private Member Const Function Virtual",
    "C Private Member Const Function Virtual Pure",
    "C Private Member Const Volatile Function",
    "C Private Member Const Volatile Function Template",
    "C Private Member Const Volatile Function Virtual",
    "C Private Member Const Volatile Function Virtual Pure",
    "C Private Member Function",
    "C Private Member Function Template",
    "C Private Member Function Explicit",
    "C Private Member Function Explicit Template",
    "C Private Member Function Static",
    "C Private Member Function Static Template",
    "C Private Member Function Virtual",
    "C Private Member Function Virtual Pure",
    "C Private Member Volatile Function",
    "C Private Member Volatile Function Template",
    "C Private Member Volatile Function Virtual",
    "C Private Member Volatile Function Virtual Pure",
    "C Protected Member Const Function",
    "C Protected Member Const Function Template",
    "C Protected Member Const Function Virtual",
    "C Protected Member Const Function Virtual Pure",
    "C Protected Member Const Volatile Function",
    "C Protected Member Const Volatile Function Template",
    "C Protected Member Const Volatile Function Virtual",
    "C Protected Member Const Volatile Function Virtual Pure",
    "C Protected Member Function",
    "C Protected Member Function Template",
    "C Protected Member Function Explicit",
    "C Protected Member Function Explicit Template",
    "C Protected Member Function Static",
    "C Protected Member Function Static Template",
    "C Protected Member Function Virtual",
    "C Protected Member Function Virtual Pure",
    "C Protected Member Volatile Function",
    "C Protected Member Volatile Function Template",
    "C Protected Member Volatile Function Virtual",
    "C Protected Member Volatile Function Virtual Pure",
    "C Public Member Const Function",
    "C Public Member Const Function Template",
    "C Public Member Const Function Virtual",
    "C Public Member Const Function Virtual Pure",
    "C Public Member Const Volatile Function",
    "C Public Member Const Volatile Function Template",
    "C Public Member Const Volatile Function Virtual",
    "C Public Member Const Volatile Function Virtual Pure",
    "C Public Member Function",
    "C Public Member Function Template",
    "C Public Member Function Explicit",
    "C Public Member Function Explicit Template",
    "C Public Member Function Static",
    "C Public Member Function Static Template",
    "C Public Member Function Virtual",
    "C Public Member Function Virtual Pure",
    "C Public Member Volatile Function",
    "C Public Member Volatile Function Template",
    "C Public Member Volatile Function Virtual",
    "C Public Member Volatile Function Virtual Pure",
    "C Unknown Function",
    "C Unknown Function Template",
    "C Unknown Member Function",
    "C Unknown Member Function Template",
    "C Unresolved Function",
    "C Unresolved Function Template",
    "C Unresolved Function Interrupt",
    "C Unresolved Function Interrupt Template",
    "C Unresolved Function Interrupt Static",
    "C Unresolved Function Interrupt Static Template",
    "C Unresolved Function Static",
    "C Unresolved Function Static Template",
    "C Unresolved Private Member Const Function",
    "C Unresolved Private Member Const Function Template",
    "C Unresolved Private Member Const Function Virtual",
    "C Unresolved Private Member Const Function Virtual Pure",
    "C Unresolved Private Member Const Volatile Function",
    "C Unresolved Private Member Const Volatile Function Template",
    "C Unresolved Private Member Const Volatile Function Virtual",
    "C Unresolved Private Member Const Volatile Function Virtual Pure",
    "C Unresolved Private Member Function",
    "C Unresolved Private Member Function Template",
    "C Unresolved Private Member Function Explicit",
    "C Unresolved Private Member Function Explicit Template",
    "C Unresolved Private Member Function Static",
    "C Unresolved Private Member Function Static Template",
    "C Unresolved Private Member Function Virtual",
    "C Unresolved Private Member Function Virtual Pure",
    "C Unresolved Private Member Volatile Function",
    "C Unresolved Private Member Volatile Function Template",
    "C Unresolved Private Member Volatile Function Virtual",
    "C Unresolved Private Member Volatile Function Virtual Pure",
    "C Unresolved Protected Member Const Function",
    "C Unresolved Protected Member Const Function Template",
    "C Unresolved Protected Member Const Function Virtual",
    "C Unresolved Protected Member Const Function Virtual Pure",
    "C Unresolved Protected Member Const Volatile Function",
    "C Unresolved Protected Member Const Volatile Function Template",
    "C Unresolved Protected Member Const Volatile Function Virtual",
    "C Unresolved Protected Member Const Volatile Function Virtual Pure",
    "C Unresolved Protected Member Function",
    "C Unresolved Protected Member Function Template",
    "C Unresolved Protected Member Function Explicit",
    "C Unresolved Protected Member Function Explicit Template",
    "C Unresolved Protected Member Function Static",
    "C Unresolved Protected Member Function Static Template",
    "C Unresolved Protected Member Function Virtual",
    "C Unresolved Protected Member Function Virtual Pure",
    "C Unresolved Protected Member Volatile Function",
    "C Unresolved Protected Member Volatile Function Template",
    "C Unresolved Protected Member Volatile Function Virtual",
    "C Unresolved Protected Member Volatile Function Virtual Pure",
    "C Unresolved Public Member Const Function",
    "C Unresolved Public Member Const Function Template",
    "C Unresolved Public Member Const Function Virtual",
    "C Unresolved Public Member Const Function Virtual Pure",
    "C Unresolved Public Member Const Volatile Function",
    "C Unresolved Public Member Const Volatile Function Template",
    "C Unresolved Public Member Const Volatile Function Virtual",
    "C Unresolved Public Member Const Volatile Function Virtual Pure",
    "C Unresolved Public Member Function",
    "C Unresolved Public Member Function Template",
    "C Unresolved Public Member Function Explicit",
    "C Unresolved Public Member Function Explicit Template",
    "C Unresolved Public Member Function Implicit",
    "C Unresolved Public Member Function Static",
    "C Unresolved Public Member Function Static Template",
    "C Unresolved Public Member Function Virtual",
    "C Unresolved Public Member Function Virtual Pure",
    "C Unresolved Public Member Volatile Function",
    "C Unresolved Public Member Volatile Function Template",
    "C Unresolved Public Member Volatile Function Virtual",
    "C Unresolved Public Member Volatile Function Virtual Pure",
    "C Asm Function Global",
    "C Asm Function Local",
    "C Asm Unresolved Function",
    "C ObjC Method Member Function",
    "C ObjC Instance Method Member Function",
    "C ObjC Optional Method Member Function",
    "C ObjC Optional Instance Method Member Function",
    "C ObjC Unknown Method Member Function",
    "C ObjC Unknown Instance Method Member Function",
    "C ObjC Unresolved Method Member Function",
    "C ObjC Unresolved Instance Method Member Function",
    "C ObjC Unresolved Optional Method Member Function",
    "C ObjC Unresolved Optional Instance Method Member Function",
    "C Lambda Function",
  ]),
  "Label": set([
    "C Label",
    "C Unknown Label",
    "C Asm Label Global",
    "C Asm Label Local",
  ]),
  "Macro": set([
    "C Inactive Macro",
    "C Macro",
    "C Macro Functional",
    "C Macro Project",
    "C Unknown Macro",
    "C Unresolved Macro",
    "C Asm Macro",
    "C Asm Macro Functional",
    "C Asm Unresolved Macro",
  ]),
  "Namespace": set([
    "C Namespace",
    "C Namespace Alias",
  ]),
  "Object": set([
    "C Object Global",
    "C Object Global Static",
    "C Object Local",
    "C Object Local Static",
    "C Private Member Object",
    "C Private Member Object Static",
    "C Protected Member Object",
    "C Protected Member Object Static",
    "C Public Member Object",
    "C Public Member Object Static",
    "C TemplateParameter Object",
    "C Unknown Member Object",
    "C Unknown Object",
    "C Unnamed TemplateParameter Object",
    "C Unresolved Object Global",
    "C Unresolved Object Global Static",
    "C Unresolved Private Member Object Static",
    "C Unresolved Protected Member Object Static",
    "C Unresolved Public Member Object Static",
    "C ObjC Private Instance Variable Member Object",
    "C ObjC Protected Instance Variable Member Object",
    "C ObjC Public Instance Variable Member Object",
    "C ObjC Package Instance Variable Member Object",
    "C ObjC Unknown Instance Variable Member Object",
    "C ObjC Unresolved Private Instance Variable Member Object",
    "C ObjC Unresolved Protected Instance Variable Member Object",
    "C ObjC Unresolved Public Instance Variable Member Object",
    "C ObjC Unresolved Package Instance Variable Member Object",
    "C TemplateParameter Object Pack",
    "C Unnamed TemplateParameter Object Pack",
  ]),
  "Parameter": set([
    "C Parameter",
    "C Unnamed Parameter",
    "C Asm Parameter",
  ]),
  "Property": set([
    "C ObjC Property",
    "C ObjC Unknown Property",
    "C ObjC Unresolved Property",
  ]),
  "Type": set([
    "C Abstract Class Type",
    "C Abstract Class Type Template",
    "C Abstract Struct Type",
    "C Abstract Struct Type Template",
    "C Class Type",
    "C Class Type Template",
    "C Enum Type",
    "C Private Member Abstract Class Type",
    "C Private Member Abstract Class Type Template",
    "C Private Member Abstract Struct Type",
    "C Private Member Abstract Struct Type Template",
    "C Private Member Class Type",
    "C Private Member Class Type Template",
    "C Private Member Enum Type",
    "C Private Member Struct Type",
    "C Private Member Struct Type Template",
    "C Private Member Typedef Type",
    "C Private Member Union Type",
    "C Private Member Union Type Template",
    "C Protected Member Abstract Class Type",
    "C Protected Member Abstract Class Type Template",
    "C Protected Member Abstract Struct Type",
    "C Protected Member Abstract Struct Type Template",
    "C Protected Member Class Type",
    "C Protected Member Class Type Template",
    "C Protected Member Enum Type",
    "C Protected Member Struct Type",
    "C Protected Member Struct Type Template",
    "C Protected Member Typedef Type",
    "C Protected Member Union Type",
    "C Protected Member Union Type Template",
    "C Public Member Abstract Class Type",
    "C Public Member Abstract Class Type Template",
    "C Public Member Abstract Struct Type",
    "C Public Member Abstract Struct Type Template",
    "C Public Member Class Type",
    "C Public Member Class Type Template",
    "C Public Member Enum Type",
    "C Public Member Struct Type",
    "C Public Member Struct Type Template",
    "C Public Member Typedef Type",
    "C Public Member Union Type",
    "C Public Member Union Type Template",
    "C Struct Type",
    "C Struct Type Template",
    "C TemplateParameter Type",
    "C Typedef Type",
    "C Union Type",
    "C Union Type Template",
    "C Unknown Class Type",
    "C Unknown Class Type Template",
    "C Unknown Enum Type",
    "C Unknown Member Type",
    "C Unknown Struct Type",
    "C Unknown Struct Type Template",
    "C Unknown Type",
    "C Unknown Union Type",
    "C Unknown Union Type Template",
    "C Unnamed Class Type",
    "C Unnamed Enum Type",
    "C Unnamed Private Member Class Type",
    "C Unnamed Private Member Enum Type",
    "C Unnamed Private Member Struct Type",
    "C Unnamed Private Member Union Type",
    "C Unnamed Protected Member Class Type",
    "C Unnamed Protected Member Enum Type",
    "C Unnamed Protected Member Struct Type",
    "C Unnamed Protected Member Union Type",
    "C Unnamed Public Member Class Type",
    "C Unnamed Public Member Enum Type",
    "C Unnamed Public Member Struct Type",
    "C Unnamed Public Member Union Type",
    "C Unnamed Struct Type",
    "C Unnamed Union Type",
    "C Unnamed TemplateParameter Type",
    "C Unresolved Class Type",
    "C Unresolved Class Type Template",
    "C Unresolved Enum Type",
    "C Unresolved Private Member Class Type",
    "C Unresolved Private Member Class Type Template",
    "C Unresolved Private Member Enum Type",
    "C Unresolved Private Member Struct Type",
    "C Unresolved Private Member Struct Type Template",
    "C Unresolved Private Member Typedef Type",
    "C Unresolved Private Member Union Type",
    "C Unresolved Private Member Union Type Template",
    "C Unresolved Protected Member Class Type",
    "C Unresolved Protected Member Class Type Template",
    "C Unresolved Protected Member Enum Type",
    "C Unresolved Protected Member Struct Type",
    "C Unresolved Protected Member Struct Type Template",
    "C Unresolved Protected Member Typedef Type",
    "C Unresolved Protected Member Union Type",
    "C Unresolved Protected Member Union Type Template",
    "C Unresolved Public Member Class Type",
    "C Unresolved Public Member Class Type Template",
    "C Unresolved Public Member Enum Type",
    "C Unresolved Public Member Struct Type",
    "C Unresolved Public Member Struct Type Template",
    "C Unresolved Public Member Typedef Type",
    "C Unresolved Public Member Union Type",
    "C Unresolved Public Member Union Type Template",
    "C Unresolved Struct Type",
    "C Unresolved Struct Type Template",
    "C Unresolved Typedef Type",
    "C Unresolved Union Type",
    "C Unresolved Union Type Template",
    "C ObjC Class Type",
    "C ObjC Protocol Type",
    "C ObjC Category Type",
    "C ObjC Unknown Class Type",
    "C ObjC Unknown Protocol Type",
    "C ObjC Unknown Category Type",
    "C ObjC Unresolved Class Type",
    "C ObjC Unresolved Protocol Type",
    "C ObjC Unresolved Category Type",
    "C TemplateParameter Type Pack",
    "C Unnamed TemplateParameter Type Pack",
  ]),
}

RefMap = {
  "Alias": set([
    "C Alias",
  ]),
  "Call": set([
    "C Asm Call",
    "C Call",
    "C Call Virtual",
    "C Call Implicit",
    "C Deref Call",
    "C Inactive Call",
    "C ObjC Message Call",
  ]),
  "Declare": set([
    "C Declare",
    "C Declare Implicit",
    "C Declare Using",
    "C Declare Default",
    "C Declare Delete",
  ]),
  "Define": set([
    "C Define",
  ]),
  "End": set([
    "C End",
  ]),
  "Friend": set([
    "C Friend",
  ]),
  "Include": set([
    "C Inactive Include",
    "C Include",
    "C Implicit Include",
  ]),
  "Modify": set([
    "C Deref Modify",
    "C Modify",
  ]),
  "Name": set([
    "C Name",
  ]),
  "ObjC Adopt": set([
    "C ObjC Adopt",
  ]),
  "ObjC Extend": set([
    "C ObjC Extend",
    "C ObjC Implement Extend",
  ]),
  "ObjC Implement": set([
    "C ObjC Implement",
    "C ObjC Implement Extend",
  ]),
  "Set": set([
    "C Deref Set",
    "C Set",
    "C Set Init",
    "C Set Init Implicit",
  ]),
  "Typed": set([
    "C Typed",
    "C Typed Implicit",
  ]),
  "Use": set([
    "C Addr Use",
    "C Addr Use Return",
    "C Asm Use",
    "C Cast Use",
    "C Deref Use",
    "C Deref Use Return",
    "C Inactive Use",
    "C Use",
    "C Use Macrodefine",
    "C Use Macroexpand",
    "C Use Ptr",
    "C Use Return",
    "C Use Capture",
    "C Use Expand",
  ]),
  "Using": set([
    "C Declare Using",
    "C Declarein Using",
    "C Using",
  ]),
  "Allow": set([
    "C Allow Exception",
  ]),
  "Base": set([
    "C Private Base",
    "C Protected Base",
    "C Public Base",
    "C Virtual Private Base",
    "C Virtual Protected Base",
    "C Virtual Public Base",
    "C ObjC Base",
  ]),
  "Catch": set([
    "C Catch Exception",
  ]),
  "Overrides": set([
    "C Overrides",
  ]),
  "Throw": set([
    "C Throw Exception",
  ]),
}

